/* Josh Janda - joshlj2 */
/* HW04 Submission */

/* INSTRUCTIONS */
/* 	Remember to save this template file as HW02_YourNetID.sas before officially
	submitting your SAS file. 	Please delete this Instructions section before
	submitting.

 	The ODS statement at the top followed by the one at the end of the file
   	will put all of the output generated by the code in between into a
	single RTF (Rich Text Format) file. This file can be opened in Word
	(or any word processor). Insert your responses to the exercise questions
	in the Word document, then save the final result as a PDF file.

	That is your report for HW04. */

/****************/

libname hw4 '/folders/myfolders/HW4/';

/*1a*/
proc sort data=hw4.PURCHASE;
	by Model;
run;
proc sort data=hw4.INVENTORY;
	by Model;
run;

data hw4.purchase_price_joshlj2;
	MERGE hw4.INVENTORY(in=inInv)
		  hw4.PURCHASE(in=inPur);
	by Model;
	if inInv and inPur;
	TotalCost = Quantity*Price;

	format TotalCost DOLLAR8.2;
run;

/*1b*/
proc print data=hw4.purchase_price_joshlj2 NOOBS;
run;

/*1c*/
data hw4.not_purchased_joshlj2(KEEP = Model
									  Price);
	merge hw4.INVENTORY(in=inInv)
		  hw4.PURCHASE(in=inPur);
	by Model;
	if not inPur;
run;

/*1d*/
proc print data=hw4.not_purchased_joshlj2 NOOBS;
run;

/*1e*/
data hw4.purchase_price_joshlj2
	 hw4.not_purchased_joshlj2(KEEP = Model
	 								  Price);
	 merge hw4.INVENTORY(in=inInv)
	 	   hw4.PURCHASE(in=inPur);
	 by Model;
	 if inInv and inPur then do;
	 	TotalCost = Quantity*Price;
	 	format TotalCost DOLLAR8.2;
	 	output hw4.purchase_price_joshlj2;
	 end;

	 if not inPur;
	 	output hw4.not_purchased_joshlj2;
run;

/*2a*/
proc contents data=hw4._ALL_;
	ods select attributes;
run;

/*2b*/
DATA hw4.fmli2014_joshlj2;
	SET hw4.fmli141
		hw4.fmli142
		hw4.fmli143
		hw4.fmli144;
	if "01" <= QINTRVMO <= "03" then
		QTR = 1;
	if "04" <= QINTRVMO <= "06" then
		QTR = 2;
	if "07" <= QINTRVMO <= "09" then
		QTR = 3;
	if "10" <= QINTRVMO <= "12" then
		QTR = 4;
run;

/*2c*/
proc contents data=hw4.fmli2014_joshlj2;
	ods select attributes;
run;

/*2d*/
DATA hw4.memi2014_joshlj2;
	SET hw4.memi141(in=inM1)
		hw4.memi142(in=inM2)
		hw4.memi143(in=inM3)
		hw4.memi144(in=inM4);
	if inM1 then
		QTR = 1;
	if inM2 then
		QTR = 2;
	if inM3 then
		QTR = 3;
	if inM4 then
		QTR = 4;
run;

/*2e*/
proc contents data=hw4.memi2014_joshlj2;
	ods select attributes;
run;

/*2f*/
proc format;
	value salaryx low-<13000 = 'Impoverished'
				   45000-90000 = 'Middle Class'
				   90000 < - < 125000 = 'Upper Middle Class'
				   125000-high = 'Upper Class'
				   . = 'Missing'
				   other = 'Lower Class';
run;

proc freq data=hw4.memi2014_joshlj2;
	format SALARYX salaryx.;
	tables SALARYX /nocum;
run;
proc freq data=hw4.memi2014_joshlj2;
	format SALARYX salaryx.;
	tables SALARYX*QTR /nocum nocol norow;
run;

/*2g*/
proc sort data=hw4.fmli2014_joshlj2;
	by NEWID;
run;
proc sort data=hw4.memi2014_joshlj2;
	by NEWID;
run;

data hw4.ce2014_joshlj2;
	merge hw4.memi2014_joshlj2(in=inM)
		  hw4.fmli2014_joshlj2(in=inF);
	by NEWID;
run;

/*2h*/
proc contents data=hw4.ce2014_joshlj2;
	ods select attributes;
run;

/*2i*/
proc sort data=hw4.fmli2014_joshlj2;
	by CUID;
run;

data hw4.atleast_three_joshlj2(KEEP=CUID);
	 set hw4.fmli2014_joshlj2;
	 by CUID;
	 
	 if First.CUID then TotalInterviews = 0;
	 	TotalInterviews+1;
	 if Last.Cuid;
	 
	 if TotalInterviews >= 3;
run;

data hw4.all_four_joshlj2(KEEP=CUID);
	 set hw4.fmli2014_joshlj2;
	 by CUID;
	 
	 if First.CUID then TotalInterviews = 0;
	 	TotalInterviews+1;
	 if Last.Cuid;
	 
	 if TotalInterviews = 4;
run;

proc contents data=hw4.atleast_three_joshlj2;
	ods select attributes;
run;

proc contents data=hw4.all_four_joshlj2;
	ods select attributes;
run;