/* Josh Janda - joshlj2 */
/* HW06 Submission */

/* INSTRUCTIONS */
/* 	Remember to save this template file as HW02_YourNetID.sas before officially
	submitting your SAS file. 	Please delete this Instructions section before
	submitting.

 	The ODS statement at the top followed by the one at the end of the file
   	will put all of the output generated by the code in between into a
	single RTF (Rich Text Format) file. This file can be opened in Word
	(or any word processor). Insert your responses to the exercise questions
	in the Word document, then save the final result as a PDF file.

	That is your report for HW06. */

/****************/

libname hw6 '/folders/myfolders/HW6/';
ods rtf file='/folders/myfolders/HW6/HW6_joshlj2.rtf';

proc sql;
	
	title "1a";
	/*1a*/
	select Name, Team, Position, Salary
	from sashelp.Baseball
	where Salary > 2000;
	
	title "1b";
	/*1b*/
	select Position, count(Position) as Position_Count
	from sashelp.Baseball
	group by Position
	having count(Position) >= 15;
	
	title "1c";
	/*1c*/
	select Division, League, count(League) as Division_Count
	from sashelp.Baseball
	group by Division, League;
	
	title "1d";
	/*1d*/
	select Name, Team, YrMajor, CrHome
	from sashelp.Baseball
	where CrHome >=20
		and YrMajor >= 2
		and YrMajor <=5;
	
	title "1e";
	/*1e*/
	describe table sashelp.Baseball;

	/*2*/
	
	title "2a";
	/*a*/
	select *
	from sashelp.shoes
	where subsidiary = "Singapore";
	
	title "2b";
	/*b*/
	select *
	from sashelp.shoes
	where subsidiary = "Singapore" AND
		  sales = (select max(sales) from sashelp.shoes
		  		   WHERE subsidiary = "Singapore");
		  		   
	title "2c";
	/*c*/
	select *
	from sashelp.shoes
	where subsidiary = "Singapore" AND
		  stores = (select max(stores) from sashelp.shoes
		  			WHERE subsidiary = "Singapore");
		  			
	title "2d";
	/*d*/
	select sum(inventory) as SumInventory,
		   avg(inventory) as AvgInventory,
		   min(inventory) as MinInventory,
		   max(inventory) as MaxInventory,
		   subsidiary
	from sashelp.shoes
	where region = "Asia"
	group by subsidiary;
	
	title "2e";
	/*e*/
	select sum(inventory) as MaxSumInventory, subsidiary
	from sashelp.shoes
	where region = "Asia"
	group by subsidiary
	having sum(inventory) >= all(select sum(inventory)
							  from sashelp.shoes
							  where region = "Asia"
							  group by subsidiary);
							  
	title "2f";
	/*f*/
	select sum(inventory) as MinSumInventory, subsidiary
	from sashelp.shoes
	where region = "Asia"
	group by subsidiary
	having sum(inventory) <= all(select sum(inventory)
							 	 from sashelp.shoes
							  	 where region = "Asia"
							     group by subsidiary);

	/*3*/

	title "3a";
	/*a*/
	describe table hw6.batting;
	
	title "3b";
	/*b*/
	select PlayerID,
		   YearID,
		   TeamID,
		   H
	from hw6.batting
	where H >= 245;
	
	title "3c";
	/*c*/
	select min(YearID) as MinYear,
		   max(YearID) as MaxYear,
		   LgID
	from hw6.batting
	group by LgID;
	
	title "3d";
	/*d*/			   
	select HR, YearID, PlayerID
	from hw6.batting as outBatting
	where HR >= 50 and HR = (select max(HR) from hw6.batting as inBatting
					   where HR >= 50 and
					   inBatting.YearID = outBatting.YearID
					   group by inBatting.YearID)
	order by YearID;

quit;
ods rtf close;