
/* Josh Janda - joshlj2 */
/* HW01 Submission */

/* INSTRUCTIONS */
/* 	Remember to save this template file as HW01_YourNetID.sas before officially
	submitting your SAS file. 	Please delete this Instructions section before 
	submitting. 

 	The ODS statement at the top followed by the one at the end of the file
   	will put all of the output generated by the code in between into a 
	single RTF (Rich Text Format) file. This file can be opened in Word
	(or any word processor). Insert your responses to the exercise questions 
	in the Word document, then save the final result as a PDF file.

	That is your report for HW01. */

/****************/

libname hw01 '/folders/myfolders/HW1';
ods rtf file='/folders/myfolders/HW1/HW01_joshlj2.rtf' ;


/* Exercise 1 */
title 'Exercise 1';

PROC CONTENTS DATA=sashelp.shoes;
	ods select attributes variables;
run;

PROC PRINT DATA=sashelp.shoes;
	where subsidiary='Singapore';
	var subsidiary product stores sales inventory returns;
run;

PROC MEANS DATA=sashelp.shoes sum mean min max;
	where region='Asia';
	class subsidiary;
	var inventory;
run;


/* Exercise 2 */
title 'Exercise 2';

PROC CONTENTS DATA=sashelp.baseball;
	ods select attributes variables;
run;

PROC PRINT data=sashelp.baseball;
	where salary > 2000;
	var name team position salary;
run;

PROC FREQ data=sashelp.baseball;
	tables position;
run;

PROC FREQ data=sashelp.baseball;
	tables league*division;
run;

PROC PRINT data=sashelp.baseball;
	where yrmajor <= 5 AND yrmajor >= 2;
	var name team yrmajor crhome;
run;

ods rtf close;
title;


