
/* Josh Janda - joshlj2 */
/* HW02 Submission */

/* INSTRUCTIONS */
/* 	Remember to save this template file as HW02_YourNetID.sas before officially
	submitting your SAS file. 	Please delete this Instructions section before 
	submitting. 

 	The ODS statement at the top followed by the one at the end of the file
   	will put all of the output generated by the code in between into a 
	single RTF (Rich Text Format) file. This file can be opened in Word
	(or any word processor). Insert your responses to the exercise questions 
	in the Word document, then save the final result as a PDF file.

	That is your report for HW02. */

/****************/

libname hw02 '/folders/myfolders/HW2';
ods rtf file='/folders/myfolders/HW2/HW02_joshlj2.rtf' ;


/* Exercise 1 */
title 'Exercise 1a';
PROC CONTENTS data=hw02.fmli143;
	ods select attributes variables;
run;

PROC CONTENTS data=hw02.memi143;
	ods select attributes variables;
run;

title 'Exercise 1b';
PROC FORMAT;
	value $bls_urbn '1' = 'Urban'
					'2' = 'Rural'
					other = 'NA';
	value $educ_ref '00' = 'Never attended school'
					'10' = 'First through eighth grade'
					'11' = 'Ninth through twelfth grade (no H.S. diploma)'
					'12' = 'High school graduate'
					'13' = 'Some college, less than college graduate'
					'14' = 'Associate’s degree (occupational/vocational or academic)'
					'15' = 'Bachelor’s degree'
					'16' = 'Master’s degree, (professional/Doctorate degree)*'
					other = 'NA';
	value $marital '1' = 'Married'
					'2' = 'Widowed'
					'3' = "Divorced"
					'4' = 'Separated'
					'5' = 'Never Married';
	value $QINTRVMO '01' = "January"
					'02' = 'February'
					'03' = 'March'
					'04' = 'April'
					'05' = 'May'
					'06' = 'June'
					'07' = 'July'
					'08' = 'August'
					'09' = 'September'
					'10' = 'October'
					'11' = 'November'
					'12' = 'December';
	value $race '1' = 'White'
				'2' = 'Black'
				'3' = 'Native American'
				'4' = 'Asian'
				'5' = 'Pacific Islander'
				'6' = 'Multi-race';
	value $region '1' = 'Northeast'
				  '2' = 'Midwest'
				  '3' = 'South'
				  '4' = 'West';
				  
	value $sex '1' = 'Male'
			   '2' = 'Female';
	value $inclass  '01' = 'Less than $5,000'
					'02' = '$5,000 to $9,999'
					'03' = '$10,000 to $14,999'
				    '04' = '$15,000 to $19,999'
					'05' = '$20,000 to $29,999'
					'06' = '$30,000 to $39,999'
					'07' = '$40,000 to $49,999'
					'08' = '$50,000 to $69,999'
					'09' = '$70,000 and over';
	value $state '01' = 'Alabama' 
	            '29' = 'Missouri'
				'02' = 'Alaska' 
				'30' = 'Montana'
				'04' = 'Arizona'
				'31' = 'Nebraska'
				'05' = 'Arkansas' 
				'32' = 'Nevada'
				'06' = 'California' 
				'33' = 'New Hampshire'
				'08' = 'Colorado'
				'34' = 'New Jersey'
				'09' = 'Connecticut'
				'36' = 'New York'
				'10' = 'Delaware'
				'37' = 'North Carolina'
				'11' = 'District of Columbia'
				'39' = 'Ohio'
				'12' = 'Florida'
				'40' = 'Oklahoma'
				'13' = 'Georgia'
				'41' = 'Oregon'
				'15' = 'Hawaii'
				'42' = 'Pennsylvania'
				'16' = 'Idaho' 
				'44' = 'Rhode Island'
				'17' = 'Illinois'
				'45' = 'South Carolina'
				'18' = 'Indiana' 
				'46' = 'South Dakota'
				'20' = 'Kansas'
				'47' = 'Tennessee'
				'21' = 'Kentucky'
				'48' = 'Texas'
				'22' = 'Louisiana' 
				'49' = 'Utah'
				'23' = 'Maine' 
				'51' = 'Virginia'
				'24' = 'Maryland'
				'53' = 'Washington'
				'25' = 'Massachuse';
	value $inclasstwo '1' = 'Less than 0.1667'
					   '2' = '0.1667 – 0.3333'
					   '3' = '0.3334 – 0.4999'
					   '4' = '0.5000 – 0.6666'
					   '5' = '0.6667 – 0.8333'
					   '6' = '0.8334 – 1.0000';
	value $cu_code '1' = 'Reference person'
				   '2' = 'Spouse'
				    '3' = 'Child or adopted child'
				    '4' = 'Grandchild'
				    '5' = 'In-law'
				    '6' = 'Brother or sister'
				    '7' = 'Mother or father'
				    '8' = 'Other related person'
				    '9' = 'Unrelated person'
				    '0' = 'Unmarried Partner';
	value $educa '1' =  'No schooling completed, or less than 1 year'
				 '2' =  'Nursery, kindergarten, and elementary (grades 1-8)'
				 '3' =  'High school (grades 9-12, no degree)'
				 '4' = 'High school graduate – high school diploma or the equivalent (GED)'
				 '5' = 'Some college but no degree'
				 '6' = 'Associate’s degree in college'
				 '7' = 'Bachelor’s degree (BA, AB, BS, etc.)'
				 '8' = 'Master’s professional, or doctorate degree (MA, MS, MBA, MD, JD, PhD, etc.)';
run;

DATA hw02.fmli143_joshlj2;
	SET hw02.fmli143;
	label NEWID = 'CU identification number'
		  AGE_REF = 'Age of Reference Person'
		  AGE2 = 'Age of Spouse'
		  BATHRMQ = '# of Complete Bathrooms'
		  BEDROOMQ = '# Bedrooms'
		  BLS_URBN = 'Urban/Rural'
		  EDUC_REF = "Education of Reference Person"
		  EDUCA2 = 'Education of Spouse'
		  FINCATAX = 'Amount of CU income after taxes'
		  FINCBTAX = 'Amount of CU income before taxes' 
		  HLFBATHQ = '# Half Bathrooms'
		  MARITAL1 = 'Marital Status'
		  NO_EARNR = 'Number of earners'
		  NUM_AUTO = 'Number of owned automobiles'
		  PRINEARN = 'Member number of principal earner'
		  QINTRVMO = 'Interview month'
		  QINTRVYR = 'Interview year'
		  RACE2 = 'Race of spouse'
		  REF_RACE = "Race of reference person"
		  SEX_REF = 'Sex of reference person'
		  SEX2 = 'Sex of spouse'
		  HH_CU_Q = 'Count of CUs in household'
		  HHID = 'Identifier of household with more than one CU'
		  INCLASS = 'Income class'
		  INCLASS2 = 'Income class based on INC_RANK'
		  CUID = 'Consumer unit identifying variable'
		  INTERI = 'Interview number';
	format BLS_URBN $bls_urbn.
		   EDUC_REF EDUCA2 $educ_ref.
		   MARITAL1 $marital.
		   QINTRVMO $QINTRVMO.
		   REF_RACE RACE2 $race.
		   SEX_REF SEX2 $sex.
		   REGION $region.
		   INCLASS $inclass.
		   INCLASS2 $inclasstwo.
		   STATE $state.;
run;

DATA hw02.memi143_joshlj2;
	SET hw02.memi143;
	LABEL NEWID = 'CU identification number'
	      CU_CODE = 'Member relationship to reference person'
	      EDUCA = 'Education of member'
	      MARITAL = 'Marital Status'
	      MEMBNO = 'Person line number'
	      SALARYX = 'Amount of wages or salary income received'
	      MEMBRACE = 'Race of member';
	FORMAT CU_CODE $cu_code.
	       EDUCA $educa.
	       MARITAL $marital.
	       MEMBRACE $race.
	       SEX $sex.;
run;

PROC CONTENTS data=hw02.fmli143_joshlj2;
	ods select attributes variables;
run;

PROC CONTENTS data=hw02.memi143_joshlj2;
	ods select attributes variables;
run;

title 'Exercise 1c';

proc print data=hw02.fmli143_joshlj2(obs=10);
	var NEWID
		CUID
		AGE_REF
		BLS_URBN
		MARITAL1
		FINCATAX;
run;

proc print data=hw02.memi143_joshlj2(obs=10);
	var NEWID
		CU_CODE
		MARITAL
		SALARYX;
run;

title 'Exercise 1d';

proc format;
	value salaryx low-<13000 = 'Impoverished'
				   45000-90000 = 'Middle Class'
				   90000 < - < 125000 = 'Upper Middle Class'
				   125000-high = 'Upper Class'
				   . = 'Missing'
				   other = 'Lower Class';
run;

title 'Exercise 1e';

proc datasets library = hw02 nolist;
	modify memi143_joshlj2;
	format salaryx salaryx.;
run;

title 'Exercise 1f';

proc freq data=hw02.fmli143_joshlj2;
	table BEDROOMQ * FAM_SIZE;
run;

proc freq data=hw02.fmli143_joshlj2;
	table FAM_SIZE * BATHRMQ;
run;

title 'Exercise 1g';

proc means data=hw02.memi143_joshlj2 mean median QRANGE alpha=.05 clm;
	class EDUCA;
	var SALARYX;
run;
	
title 'Exercise 1h';

proc format;
	value age 0-9 = 'Child'
			  10-19 = 'Teens'
			  20-29 = 'Twenties'
			  30-39 = 'Thirties'
			  40-49 = 'Forties'
			  50-59 = 'Fifties'
			  60-69 = 'Sixties'
			  70-79 = 'Seventies'
			  80-89 = 'Eighties'
			  90-99 = 'Nineties'
			  other = 'Miscoded';
run;

proc means data=hw02.memi143_joshlj2 mean median QRANGE alpha=.05 clm;
	class age;
	var SALARYX;
	format age age.;
run;

ods rtf close;



