/* Josh Janda - joshlj2 */
/* HW03 Submission */

/* INSTRUCTIONS */
/* 	Remember to save this template file as HW02_YourNetID.sas before officially
	submitting your SAS file. 	Please delete this Instructions section before 
	submitting. 

 	The ODS statement at the top followed by the one at the end of the file
   	will put all of the output generated by the code in between into a 
	single RTF (Rich Text Format) file. This file can be opened in Word
	(or any word processor). Insert your responses to the exercise questions 
	in the Word document, then save the final result as a PDF file.

	That is your report for HW03. */

/****************/

libname hw03 '/folders/myfolders/HW3';
ods rtf file='/folders/myfolders/HW3/HW03_joshlj2.rtf';

/*Exercise 1*/
title "Exercise 1a";

proc format;
	value $origin 'NSW' = 'New South Wales'
				 'VIC' = 'Victoria'
				 'QLD' = 'Queensland'
				 'WA' = 'Western Australia'
				 'SA' = 'South Australia'
				 'TAS' = 'Tasmania'
				 'NT' = 'Northern Territory';
	value $trans 'hs' = 'male homosexual or bisexual contact'
				 'hsid' = 'male homosexual or bisexual contact and intravenous drug user'
				 'id' = 'female or heterosexual male intravenous drug user'
				 'het' = 'heterosexual contact'
				 'haem' = 'haemophilia or coagulation disorder'
				 'blood' = 'receipt of blood, blood components or tissue'
				 'mother' = 'mother with or at risk of HIV infection'
				 'other' = 'other or unknown'
				 other = 'miscoded';
	value $sex 'M' = 'Male'
			   'F' = 'Female';
	value $status 'D' = 'Dead'
				  'A' = 'Alive';
run;

title "Exercise 1b";

data HW03.AUaids_joshlj2;
	INFILE "/folders/myfolders/HW3/AUaids.dat";
	INPUT Observation Origin $ Sex $ Diagnosis_Date
		  Death_or_End_of_Obs_Date Status $ Transmission_Category $ Age;
	LABEL Transmission_Category = "How AIDS was transmitted"
		  Age = "Age at Diagnosis";
	FORMAT Diagnosis_Date Death_or_End_of_Obs_Date MMDDYY10.
		   Origin origin.
		   Sex sex.
		   Transmission_Category trans.
		   Status status.;
run;

title "Exercise 1c";

PROC FREQ data=HW03.AUAIDS_JOSHLJ2;
	TABLE Transmission_Category /NOFREQ NOCUM;
run;

title "Exercise 1d";

data HW03.AUaids_joshlj2d;
	 INFILE "/folders/myfolders/HW3/AUaids.dat";
	 INPUT Observation Origin $ Sex $ Diagnosis_Date
		  Death_or_End_of_Obs_Date Status $ Transmission_Category $ Age;
	LABEL Transmission_Category = "How AIDS was transmitted"
		  Age = "Age at Diagnosis";
	IF Sex = "M" &
	   Age <= 24 &
	   Transmission_Category in ('hs', 'hsid', 'het');
	FORMAT Diagnosis_Date Death_or_End_of_Obs_Date MMDDYY10.
		   Origin origin.
		   Sex sex.
		   Transmission_Category trans.
		   Status status.;
run;

title "Exercise 1e";

PROC FREQ data=hw03.AUAIDS_JOSHLJ2D;
	TABLE Origin * Transmission_Category /NOROW NOCOL;
run;

/*Exercise 2*/
title 'Exercise 2a';

data hw03.rushing_joshlj2;
	INFILE "/folders/myfolders/HW3/nflrush.dat" FIRSTOBS=2;
	INPUT @3 Season 4. @13 Player $29.
		  @43 Team $4. @77 Avg_Rushing_Yds_Per_Att 7.
		  @86 Avg_Rushing_Yds_Per_Game 7.
		  @96 Longest_Rushing_Att 7. @105 Number_Rushing_Touchdowns 5.
		  @111 Rushing_First_Downs 2.;
	LABEL Avg_Rushing_Yds_Per_Att = 'Average rushing yards per game, rounded to nearest 0.01'
		  Avg_Rushing_Yds_Per_Game = 'Average rushing yards per game, rounded to nearest 0.1'
		  Longest_Rushing_Att = 'Longest rushing attempt'
		  Number_Rushing_Touchdowns = 'Number of rushing touchdowns (i.e., scores, goals)';
run;

title 'Exercise 2b';

PROC CONTENTS data=hw03.rushing_joshlj2;
	ods select attributes variables;
run;

title 'Exercise 2c';

PROC SORT data=hw03.rushing_joshlj2 out=hw03.rushing_joshlj2_sorted;
	WHERE Season >= 2013 AND Season <= 2015;
	by descending Number_Rushing_Touchdowns;
run;

PROC PRINT data=hw03.rushing_joshlj2_sorted(obs=10);
	VAR Season Player Number_Rushing_Touchdowns;
run;

title 'Exercise 2d';

data hw03.localnfl_joshlj2;
	INFILE "/folders/myfolders/HW3/nflrush_quotes.dat" FIRSTOBS=2;
	INPUT @1 Season 4. @12 Player $quote27. @39 Team $4.
		  @74 Avg_rushing_Yds_Per_Att 7.
		  @82 Avg_Rushing_Yds_Per_Game 7.
		  @92 Longest_Rushing_Att 7.
		  @101 Number_Rushing_Touchdowns 5.
		  @109 Rushing_First_Downs 2.;
	LABEL Avg_Rushing_Yds_Per_Att = 'Average rushing yards per game, rounded to nearest 0.01'
		  Avg_Rushing_Yds_Per_Game = 'Average rushing yards per game, rounded to nearest 0.1'
		  Longest_Rushing_Att = 'Longest rushing attempt'
		  Number_Rushing_Touchdowns = 'Number of rushing touchdowns (i.e., scores, goals)';
	IF TEAM in ('Stl', 'Chi', 'Ind', 'GB');
run;

title 'Exercise 2e';

PROC CONTENTS data=hw03.localnfl_joshlj2;
	ods select attributes variables;
run;

title 'Exercise 2f';

PROC SORT data=hw03.localnfl_joshlj2 out=hw03.localnfl_joshlj2_sorted;
	by descending Avg_Rushing_Yds_Per_Game;
run;

PROC PRINT data=hw03.localnfl_joshlj2_sorted(obs=10);
	VAR Season Player Team Avg_Rushing_Yds_Per_Game;
run;

/*Exercise 3*/

title 'Exercise 3a';

proc format;
	value $Sex 'M' = 'Male'
			   'F' = 'Female';
run;

data hw03.low_earners4_joshlj2;
	infile "/folders/myfolders/HW3/employee_roster4.dat" dlm = "**" missover;
	input ID :6. Name :$24. Country :$2.
	#2 Company :$24. Department :$24. Section :$28. Organization_Group :$28. Job_Title :$28. Gender :$1.
	#3 Salary :comma12. Birth_Date :8. Hire_Date :8. Termination_Date :8.;
	format Birth_Date Hire_Date Termination_Date mmddyy10.
		   Gender $Sex.;
	label Termination_Date = "Termination Date. If missing, employee still employed.";
	if find(Company, 'Orion') & Salary < 24000 & Department = 'Sales';
run;

title 'Exercise 3b';

proc contents data=hw03.low_earners4_joshlj2;
	ods select attributes variables;
run;

title 'Exercise 3c';

proc print data=hw03.low_earners4_joshlj2;
	var Name Gender Department Job_Title Salary;
run;

ods rtf close;





			