/* Josh Janda - joshlj2 */
/* HW05 Submission */

/* INSTRUCTIONS */
/* 	Remember to save this template file as HW02_YourNetID.sas before officially
	submitting your SAS file. 	Please delete this Instructions section before
	submitting.

 	The ODS statement at the top followed by the one at the end of the file
   	will put all of the output generated by the code in between into a
	single RTF (Rich Text Format) file. This file can be opened in Word
	(or any word processor). Insert your responses to the exercise questions
	in the Word document, then save the final result as a PDF file.

	That is your report for HW05. */

/****************/

libname hw5 '/folders/myfolders/HW5/';
*ods rtf file='/folders/myfolders/HW4/HW5_joshlj2.rtf';

/*1a*/

proc sort data=hw5.orders;
	by customer_id order_type;
run;

data hw5.discount_ret(KEEP=Customer_ID
						   Customer_Name
						   TotSales)
	 hw5.discount_int(KEEP=Customer_ID
						   Customer_Name
						   Customer_BirthDate
						   TotSales)
	 hw5.discount_cat(KEEP=Customer_ID
						   Customer_Name
						   Customer_Gender
						   TotSales);
						   
	set hw5.orders;
	by customer_id order_type;
	
	if First.order_type then TotSales = 0;
		TotSales + Total_Retail_Price;
	if Last.order_type;
	
	format TotSales DOLLAR8.2;
	
	if order_type = 1 and TotSales >= 400 then
		output hw5.discount_ret;
	
	if order_type = 3 and TotSales >= 400 then
		output hw5.discount_int;
		
	if order_type = 2 and TotSales >= 100 then
		output hw5.discount_cat;
	
run;

proc sort data=hw5.orders;
	by customer_id;
run;

data hw5.top_buyers_joshlj2(KEEP=Customer_ID
						   		 Customer_Name
						         TotSales);
	 set hw5.orders;
	 
	 by customer_id;
	 
	 if First.customer_id then TotSales = 0;
	 	TotSales + Total_Retail_Price;
	 if Last.customer_id;
	 
	 format TotSales DOLLAR8.2;
	 
	 if TotSales >= 600;
run;

/*1b*/
proc print data=hw5.discount_ret; 
	title "Customers who spent > $400 on retail purchases";
run;

proc print data=hw5.discount_int; 
	title "Customers who spent > $400 on internet purchases";
run;

proc print data=hw5.discount_cat; 
	title "Customers who spent > $100 on catalog purchases";
run;

proc print data=hw5.top_buyers_joshlj2; 
	title "Customers who spent > $600 across all platforms";
run;

/*2a*/
data hw5.trade_joshlj2;
	 
	 infile "/folders/myfolders/HW5/importexport87-15.dat" dlm = '09'x;
	 
	 input Date :MMDDYY10. TotExports :8. TotImports :8. @@;
	 
	 Balance = TotExports - TotImports;
	 
	 format Date MMDDYY10.
	 		TotExports DOLLAR12.2
	 		TotImports DOLLAR12.2
	 		Balance DOLLAR12.2;
run;

/*2b*/
proc print data=hw5.trade_joshlj2;
	where Date between '01JAN2011'd and '31DEC2011'd;
run;

/*2c*/
proc sort data=hw5.trade_joshlj2;
	by Date;
run;

data hw5.yearlyimports_joshlj2(KEEP=Year
									YearTotal
									YearAvg);
	
	set hw5.trade_joshlj2;
	by Date;
	
	Year = year(Date);
	Month = month(Date);

	if Month=1 then do;
		YearTotal = 0;
		TotalMonths = 0;
	end;
	
	YearTotal + TotImports;
	TotalMonths + 1;
	
	if Month=12;
	YearAvg = YearTotal / TotalMonths;
	
run;

/*2d*/
proc contents data=hw5.yearlyimports_joshlj2;
	ods select attributes variables;
run;

/*2e*/
proc print data=hw5.yearlyimports_joshlj2;
	where Year between 2000 and 2004;
run;

/*2f*/
proc format;
	value decades 1980-1989 = "1980s"
				  1990-1999 = "1990s"
				  2000-2009 = "2000s"
				  2010-2019 = "2010s";
run;

proc means data=hw5.yearlyimports_joshlj2 mean median;
	class Year;
	var YearAvg;
	format Year decades.;
run;